# Generated by Django 4.2.7 on 2025-11-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="daily_room_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
