# Generated by Django 4.2.7 on 2025-11-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_meeting_daily_room_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_appointments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_notes",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_surveys",
            field=models.BooleanField(default=True),
        ),
    ]
