# Generated by Django 4.2.7 on 2025-11-29 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromsScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score_type",
                    models.CharField(
                        choices=[
                            ("pre_surgery", "Pre-Surgery"),
                            ("post_surgery", "Post-Surgery"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField()),
                ("billable_codes", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proms_scores",
                        to="core.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proms_scores",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "db_table": "proms_scores",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
