# Generated by Django 4.2.7 on 2025-11-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_promsscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("missed", "Missed"),
                    ("transcription_pending", "Transcription Pending"),
                    ("transcription_failed", "Transcription Failed"),
                ],
                default="scheduled",
                max_length=30,
            ),
        ),
    ]
