# Generated by Django 4.2.7 on 2025-11-30 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_meeting_status"),
        ("core", "0006_peer_features"),
    ]

    operations = []
