# Generated by Django 4.2.7 on 2025-11-30 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_survey_assigned_patients"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.IntegerField(help_text="Rating from 1 to 5 stars")),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Patient recommendation/feedback",
                        null=True,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.doctor",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review",
                        to="core.meeting",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_reviews",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_reviews",
                "ordering": ["-created_at"],
                "unique_together": {("doctor", "patient")},
            },
        ),
    ]
