# Generated by Django 4.2.7 on 2025-12-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_doctorreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="connect_to_peers",
            field=models.BooleanField(
                default=False, help_text="Allow connection with other patients"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="procedure",
            field=models.CharField(
                blank=True,
                help_text="Medical procedure or treatment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, help_text="Display username", max_length=100, null=True
            ),
        ),
    ]
