# Generated by Django 4.2.7 on 2025-12-02 17:17
# Updated to work with both SQLite and PostgreSQL

from django.db import migrations, models, connection


def add_fields_safely(apps, schema_editor):
    """Add fields only if they don't exist (database-agnostic)"""
    db = schema_editor.connection
    db_vendor = connection.vendor
    
    def column_exists(table_name, column_name):
        """Check if a column exists in a table (works for SQLite and PostgreSQL)"""
        with db.cursor() as cursor:
            if db_vendor == 'sqlite':
                cursor.execute(f"PRAGMA table_info({table_name})")
                columns = [row[1] for row in cursor.fetchall()]
                return column_name in columns
            elif db_vendor == 'postgresql':
                # PostgreSQL: check information_schema, table names are case-insensitive
                cursor.execute("""
                    SELECT column_name 
                    FROM information_schema.columns 
                    WHERE table_name = LOWER(%s) AND column_name = %s
                """, [table_name, column_name])
                return cursor.fetchone() is not None
            else:
                # For other databases, use Django introspection
                from django.db import connection
                inspector = connection.introspection
                try:
                    table_description = inspector.get_table_description(cursor, table_name)
                    return any(col.name == column_name for col in table_description)
                except:
                    return False
    
    try:
        with db.cursor() as cursor:
            # Check and add doctor.city
            if not column_exists('doctors', 'city'):
                cursor.execute("ALTER TABLE doctors ADD COLUMN city VARCHAR(255) NULL")
            
            # Check and add patient fields
            if not column_exists('patients', 'age'):
                cursor.execute("ALTER TABLE patients ADD COLUMN age INTEGER NULL")
            if not column_exists('patients', 'gender'):
                cursor.execute("ALTER TABLE patients ADD COLUMN gender VARCHAR(50) NULL")
            if not column_exists('patients', 'procedure'):
                cursor.execute("ALTER TABLE patients ADD COLUMN procedure VARCHAR(255) NULL")
            if not column_exists('patients', 'connect_to_peers'):
                if db_vendor == 'sqlite':
                    cursor.execute("ALTER TABLE patients ADD COLUMN connect_to_peers BOOLEAN NOT NULL DEFAULT 0")
                else:
                    cursor.execute("ALTER TABLE patients ADD COLUMN connect_to_peers BOOLEAN NOT NULL DEFAULT FALSE")
            
            # Check and add user.username
            if not column_exists('users', 'username'):
                cursor.execute("ALTER TABLE users ADD COLUMN username VARCHAR(100) NULL")
    except Exception as e:
        # If columns already exist or other error, migration will continue
        # This is safe because we check before adding
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"Migration 0012: Some columns may already exist: {e}")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_doctorreview"),
    ]

    operations = [
        migrations.RunPython(add_fields_safely, migrations.RunPython.noop),
    ]
