# Generated by Django 4.2.7 on 2025-12-02 17:35
# This migration was auto-generated but fields may already exist from 0012
# Making it safe to handle existing columns and prevent duplicate column errors

from django.db import migrations


def check_and_add_if_needed(apps, schema_editor):
    """Check if columns exist, add only if missing (for SQLite compatibility)"""
    db = schema_editor.connection
    
    try:
        with db.cursor() as cursor:
            # Check and add doctor.city if needed
            cursor.execute("PRAGMA table_info(doctors)")
            doctor_columns = [row[1] for row in cursor.fetchall()]
            
            if 'city' not in doctor_columns:
                cursor.execute("ALTER TABLE doctors ADD COLUMN city VARCHAR(255) NULL")
            
            # Check and add patient fields if needed
            cursor.execute("PRAGMA table_info(patients)")
            patient_columns = [row[1] for row in cursor.fetchall()]
            
            if 'age' not in patient_columns:
                cursor.execute("ALTER TABLE patients ADD COLUMN age INTEGER NULL")
            if 'gender' not in patient_columns:
                cursor.execute("ALTER TABLE patients ADD COLUMN gender VARCHAR(50) NULL")
            if 'procedure' not in patient_columns:
                cursor.execute("ALTER TABLE patients ADD COLUMN procedure VARCHAR(255) NULL")
            if 'connect_to_peers' not in patient_columns:
                cursor.execute("ALTER TABLE patients ADD COLUMN connect_to_peers BOOLEAN NOT NULL DEFAULT 0")
            
            # Check and add user.username if needed
            cursor.execute("PRAGMA table_info(users)")
            user_columns = [row[1] for row in cursor.fetchall()]
            
            if 'username' not in user_columns:
                cursor.execute("ALTER TABLE users ADD COLUMN username VARCHAR(100) NULL")
    except Exception as e:
        # If there's an error (e.g., columns already exist), just log it and continue
        # The migration will be marked as applied
        print(f"Migration 0013: Some columns may already exist: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_registration_fields'),
    ]

    operations = [
        # Use RunPython to safely check before adding columns
        migrations.RunPython(check_and_add_if_needed, migrations.RunPython.noop),
    ]
